# Generated by Django 3.2 on 2021-05-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('artist', models.URLField()),
                ('tracks', models.URLField()),
                ('self_u', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('albums', models.URLField()),
                ('tracks', models.URLField()),
                ('self_a', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist', models.URLField()),
                ('album', models.URLField()),
                ('self_c', models.URLField()),
            ],
        ),
    ]
